services:
    freezybee.editrouble.twig_extension:
        class: FreezyBee\EditroubleBundle\Twig\EditroubleExtension
        arguments: [%freezy_bee_editrouble.placeholder%, %freezy_bee_editrouble.role%]
        tags:
            - { name: twig.extension }
        autowire: true

    freezybee.editrouble.model.content_provider:
        class: FreezyBee\EditroubleBundle\Model\ContentProvider
        arguments: ['@cache.app', '@freezybee.editrouble.model.storage.doctrine']

    freezybee.editrouble.model.storage.doctrine:
        class: FreezyBee\EditroubleBundle\Model\Storage\Doctrine
        arguments: ['@doctrine.orm.entity_manager']
